version: 2
workers:
- type: router
  realms:
  - name: deskconn
    options:
      enable_meta_api: false
    roles:
    - name: backend
      permissions:
        - uri: 'org.deskconn.'
          match: prefix
          allow:
            register: true

    - name: deskconn
      permissions:
        - uri: 'org.deskconn.'
          match: prefix
          allow:
            register: true
            call: true
            publish: true
            subscribe: true

    - name: cli
      permissions:
        - uri: 'org.deskconn.generate_otp'
          match: exact
          allow:
            call: true
        - uri: 'org.deskconn.enable_discovery'
          match: exact
          allow:
            call: true
        - uri: 'org.deskconn.disable_discovery'
          match: exact
          allow:
            call: true
  components:
  - type: class
    realm: deskconn
    role: backend
    classname: deskconnd.components.ManagementSession
  transports:
  - type: websocket
    endpoint:
      type: tcp
      port: $DESKCONN_PORT
    auth:
      cryptosign:
        type: dynamic
        authenticator: org.deskconn.authenticate
        authenticator-realm: deskconn
