version: 2
workers:
- type: router
  realms:
  - name: deskconn
    options:
      enable_meta_api: false
    roles:
    - name: deskconn
      permissions:
        - uri: ''
          match: prefix
          allow:
            register: true
            call: true
            publish: true
            subscribe: true
    - name: anonymous
      permissions:
        - uri: 'org.deskconn.deskconnd.pairing.'
          match: prefix
          allow:
            register: true
            call: true
  components:
  - type: class
    realm: deskconn
    role: deskconn
    classname: deskconnd.components.ManagementSession
  transports:
  - type: websocket
    endpoint:
      type: tcp
      port: $DESKCONN_PORT
    auth:
      cryptosign:
        type: dynamic
        authenticator: org.deskconn.deskconnd.authenticate
        authenticator-realm: deskconn
      anonymous:
        type: static
        role: anonymous
