version: 2
workers:
- type: router
  realms:
  - name: deskconn
    options:
      enable_meta_api: false
    roles:
    - name: authenticator
      permissions:
        - uri: 'org.deskconn.deskconnd.authenticate'
          match: exact
          allow:
            register: true
            call: true
        - uri: 'org.deskconn.deskconnd.pair'
          match: exact
          allow:
            register: true
            call: true
    - name: deskconn
      permissions:
        - uri: ''
          match: prefix
          allow:
            register: true
            call: true
            publish: true
            subscribe: true
          disclose:
            caller: false
            publisher: false
          cache: false
  transports:
  - type: websocket
    endpoint:
      type: tcp
      port: $DESKCONN_PORT
    auth:
      cryptosign:
        type: dynamic
        authenticator: org.deskconn.deskconnd.authenticate
        authenticator-realm: deskconn
      anonymous:
        type: static
        role: authenticator

- type: guest
  executable: manager.py
