name: deskconnd
version: git
summary: Secure, cross-platform IPC on the network
description: |
  Secure, cross-platform IPC on the network

  * Communication over WAMP
  * Supports multiple programming languages
  * End-to-end encryption by default

  https://github.com/deskconn/deskconnd

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: i386
    run-on: i386

  - build-on: armhf
    run-on: armhf

environment:
  PYTHONPATH: $PYTHONPATH:$SNAP_COMMON/crossbar-runtime-dir/crossbar:$SNAP/packages
  PATH: $PATH:$SNAP_COMMON/crossbar-runtime-dir/crossbar/bin:$SNAP_COMMON/crossbar-runtime-dir/usr/bin

parts:
  launchers:
    plugin: dump
    source: .
    prime:
      - cli.py
      - scripts/daemon.sh
      - .crossbar.yaml
    stage:
      - cli.py
      - scripts/daemon.sh
      - .crossbar.yaml
  deskconn:
    plugin: nil
    source: .
    override-build: |
      snapcraftctl build
      add-apt-repository ppa:deadsnakes/ppa -y -u
      apt install python3.8 python3.8-venv python3.8-dev -y
      PY=/usr/bin/python3.8
      rm -rf packages
      mkdir packages
      $PY -m ensurepip
      $PY -m pip install -t packages .
      cp -r packages ${SNAPCRAFT_PART_INSTALL}
    build-packages:
      - software-properties-common

apps:
  deskconnd:
    command: scripts/daemon.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
  deskconnctl:
    command: cli.py
    plugs:
      - network
      - network-bind

plugs:
  crossbar-runtime-dir:
    content: executables
    default-provider: crossbar:runtime-dir
    interface: content
    target: $SNAP_COMMON/crossbar-runtime-dir
