$schema: https://raw.githubusercontent.com/crossbario/crossbar/master/crossbar.json
version: 2
controller: {}
workers:
- type: router
  realms:
  - name: deskconn
    roles:
    - name: pairing
      permissions:
      - uri: 'org.deskconn.pairing.'
        match: prefix
        allow:
          call: true
          register: true
          publish: false
          subscribe: false
        disclose:
          caller: false
          publisher: false
        cache: false
    - name: deskconn
      permissions:
      - uri: 'org.deskconn.'
        match: prefix
        allow:
          call: true
          register: true
          publish: true
          subscribe: true
        disclose:
          caller: false
          publisher: false
        cache: true
    - name: discovery
      permissions:
      - uri: ''
        match: exact
        allow:
          call: false
          register: false
          publish: false
          subscribe: false
        disclose:
          caller: false
          publisher: false
        cache: false
  components:
  - type: class
    realm: deskconn
    classname: deskconnd.components.pairing.PairingComponent
    role: pairing
  - type: class
    realm: deskconn
    classname: deskconnd.components.pairing.AuthenticatorSession
    role: deskconn
  - type: class
    realm: deskconn
    classname: deskconnd.components.discovery.ServiceDiscoveryComponent
    role: discovery
  transports:
  - type: websocket
    endpoint:
      type: tcp
      port: 5020
    auth:
      anonymous:
        type: static
        role: pairing
      cryptosign:
        type: dynamic
        authenticator: org.deskconn.authenticate
        authenticator-realm: deskconn
  - type: rawsocket
    endpoint:
      type: unix
      path: $DESKCONND_SOCK_DIR/deskconnd.sock
    auth:
      anonymous:
        type: static
        role: deskconn
