version: 2
controller: {}
workers:
- type: router
  realms:
  - name: deskconn
    roles:
    - name: deskconn
      permissions:
        - uri: ''
          match: prefix
          allow:
            register: true
            call: true
            publish: true
            subscribe: true
          disclose:
            caller: false
            publisher: false
          cache: true
    - name: authenticator
      permissions:
        - uri: org.deskconn.deskconnd.authenticate
          match: exact
          allow:
            register: true
          disclose:
            caller: false
            publisher: false
          cache: true
  components:
  - type: class
    realm: deskconn
    role: deskconn
    classname: deskconnd.components.pairing.PairingSession
  - type: class
    realm: deskconn
    role: authenticator
    classname: deskconnd.components.authentication.AuthSession
  - type: class
    realm: deskconn
    role: deskconn
    classname: deskconnd.components.discovery.ServiceDiscoverySession
  transports:
  - type: websocket
    endpoint:
      type: tcp
      port: 5020
    auth:
      cryptosign:
        type: dynamic
        authenticator: org.deskconn.deskconnd.authenticate
        authenticator-realm: deskconn
