name: deskconnd
version: git
summary: Secure, cross-platform IPC on the network
description: |
  Secure, cross-platform IPC on the network

  * Communication over WAMP
  * Supports multiple programming languages
  * End-to-end encryption by default

  https://github.com/deskconn/deskconnd

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: i386
    run-on: i386

  - build-on: armhf
    run-on: armhf

  - build-on: arm64
    run-on: arm64

environment:
  PYTHONPYCACHEPREFIX: $SNAP_DATA/pycache
  PYTHONPATH: $PYTHONPATH:$SNAP/packages

parts:
  deskconn:
    plugin: py38
    source: .
    stage-packages:
      # Required by Crossbar
      - libsnappy1v5
      - libunwind8
    build-packages:
      - build-essential
      - gcc
      - libffi-dev
      - libssl-dev
      - make
      - libbz2-dev
      # Required by Crossbar
      - libsnappy-dev
      - libunwind-dev
  launchers:
    plugin: dump
    source: .
    prime:
      - cli.py
      - scripts/daemon.sh
      - .crossbar.yaml
    stage:
      - cli.py
      - scripts/daemon.sh
      - .crossbar.yaml

apps:
  deskconnd:
    command: scripts/daemon.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
  deskconnctl:
    command: cli.py
    plugs:
      - network
      - network-bind

slots:
  state:
    interface: content
    read:
      - $SNAP_COMMON/state
