name: deskconnd
version: git
summary: Secure, cross-platform IPC on the network
description: |
  Secure, cross-platform IPC on the network

  * Communication over WAMP
  * Supports multiple programming languages
  * End-to-end encryption by default

  https://github.com/deskconn/deskconnd

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: i386
    run-on: i386

  - build-on: armhf
    run-on: armhf

  - build-on: arm64
    run-on: arm64

environment:
  PATH: $PATH:/snap/core18/current/usr/bin:$SNAP/bin
  PYTHONPATH: $PYTHONPATH:$SNAP/lib/python3.6/site-packages

parts:
  deskconn:
    plugin: nil
    source: .
    override-build: |
      snapcraftctl build
      python3 -O -m pip install --ignore-installed -U --no-compile --prefix $SNAPCRAFT_PART_INSTALL .
      rm -r $SNAPCRAFT_PART_INSTALL/lib/python3.6/site-packages/numpy
      python3 -O -m compileall -b -x .*\.syntaxerror.py$ $SNAPCRAFT_PART_INSTALL
      find $SNAPCRAFT_PART_INSTALL -type f -name "*.py" -exec rm {} \;
      find $SNAPCRAFT_PART_INSTALL -type f -name "*.so" -exec strip -s {} \;
    stage-packages:
      - libsnappy1v5
      - libunwind8
    build-packages:
      - build-essential
      - gcc
      - libffi-dev
      - libssl-dev
      - make
      - libbz2-dev
      - libsnappy-dev
      - libunwind-dev
      - python3-pip
  launchers:
    plugin: dump
    source: .
    prime:
      - cli.py
      - scripts/daemon.sh
      - .crossbar.yaml
    stage:
      - cli.py
      - scripts/daemon.sh
      - .crossbar.yaml

apps:
  deskconnd:
    command: scripts/daemon.sh
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
  deskconnctl:
    command: cli.py
    plugs:
      - network
      - network-bind

slots:
  runtime:
    interface: content
    content: runtime
    read:
      - $SNAP
  state:
    interface: content
    content: state
    read:
      - $SNAP_COMMON/state
