name: deskconnd
version: git
summary: Expose your desktop functionalities over network
description: |
  Expose your desktop functionalities over network

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: i386
    run-on: i386

  - build-on: armhf
    run-on: armhf

environment:
  PYTHONPATH: PYTHONPATH:$SNAP_COMMON/crossbar-runtime-dir

parts:
  launchers:
    plugin: dump
    source: .
    stage:
      - pair.py
      - server.py
      - .crossbar
    prime:
      - pair.py
      - server.py
      - .crossbar
  deskconn:
    plugin: python
    source: .
    python-packages:
      - sqlitedict

apps:
  deskconnd:
    command: server.py
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
  pair:
    command: pair.py
    plugs:
      - network
      - network-bind

slots:
  sock-dir:
    interface: content
    content: socket-directory
    write:
      - $SNAP_COMMON/deskconnd-sock-dir

plugs:
  discovery:
    content: avahi-services
    default-provider: avahi:services-content
    interface: content
    target: $SNAP_COMMON/avahi-services-dir
  crossbar-runtime-dir:
    content: executables
    default-provider: crossbar:runtime-dir
    interface: content
    target: $SNAP_COMMON/crossbar-runtime-dir
